---
abstract: 'watch the file updates'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-watcher
no_index:
  directory:
    - t
    - inc
provides:
  App::watcher:
    file: lib/App/watcher.pm
    version: 0.08
requires:
  Filesys::Notify::Simple: 0
  Linux::Inotify2: 0
  perl: 5.008008
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
